from pprint import pprint

# This is representative of the inheritance of the classes below
#      A         Ancient Ancestor (or "Great Great Grandparent")
#     / \
#    B   C       Great Grandparents
#   / \ / \
#  D   E   F     Grandparents
#   \ / \ /
#    G   H       Parents
#     \ /
#      I         Child


# This Python code is totally valid, it just doesn't adhere to PEP8 standards
class A: ...
class B(A): ...
class C(A): ...
class D(B): ...
class E(B, C): ...
class F(C): ...
class G(D, E): ...
class H(E, F): ...
class I(G, H): ...


if __name__ == "__main__":
    pprint(I.mro())
